# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_no', models.CharField(max_length=200, unique=True)),
                ('surname', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight')], max_length=10)),
                ('year', models.DateField()),
                ('teacher', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Science', 'Science'), ('Social Studies', 'Social Studies')], max_length=20)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thewema.StudentClass'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thewema.Subject'),
        ),
    ]
