# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='thewema.StudentClass'),
        ),
    ]
