# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0005_auto_20170312_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='year',
            field=models.DateField(blank=True),
        ),
    ]
