# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0006_auto_20170312_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
