# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0009_auto_20170313_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='year',
            field=models.DateField(),
        ),
    ]
