# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0010_auto_20170325_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
    ]
