# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0011_auto_20170325_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='year',
            field=models.CharField(choices=[('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000')], max_length=10),
        ),
    ]
