# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0013_auto_20170325_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'ordering': ['-year']},
        ),
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together=set([('standard', 'year')]),
        ),
    ]
