# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0016_auto_20170325_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='etype',
            field=models.CharField(choices=[('Opening-Term', 'Opening-Term'), ('Mid-Term', 'Mid-Term'), ('End-Term', 'End-Term')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('TERM 1', 'TERM 1'), ('TERM 2', 'TERM 2'), ('TERM 3', 'TERM 3')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thewema.Exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='sclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thewema.StudentClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thewema.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thewema.StudentClass'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set([('term', 'etype')]),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('student', 'sclass', 'exam')]),
        ),
    ]
