# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0018_score_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(max_length=200),
        ),
    ]
