# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0019_auto_20170327_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([]),
        ),
    ]
