# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0020_auto_20170327_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='sclass',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('student', 'exam')]),
        ),
    ]
