# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0021_auto_20170329_2121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([]),
        ),
    ]
