# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0023_auto_20170329_2304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('student', 'exam')]),
        ),
    ]
