# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0024_auto_20170330_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('student', 'exam', 'subject')]),
        ),
    ]
