# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0025_auto_20170330_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='marks',
            field=models.PositiveSmallIntegerField(max_length=200),
        ),
    ]
