# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0026_auto_20170330_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
