# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0027_auto_20170330_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
