# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0028_auto_20170330_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
