# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewema', '0030_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('Correction', 'Correction'), ('Feedback', 'Feedback'), ('Support', 'Support')], max_length=200),
        ),
    ]
